---
- name: Install and configure Nginx with custom index
  hosts: all
  become: yes
  vars:
    index_file: "{{ 'index-aws.html' if inventory_hostname in groups['aws'] else 'index-azure.html' }}"
    cloud_name: "{{ 'AWS' if inventory_hostname in groups['aws'] else 'Azure' }}"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"


    - name: Ensure Nginx service is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Rename default index.html if exists
      command: mv /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bak
      args:
        removes: /var/www/html/index.html      

    - name: Copy custom index file
      copy:
        src: "files/{{ index_file }}"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Ensure Nginx is serving the new page
      shell: systemctl restart nginx
      args:
        warn: false

    - name: Verify Nginx is running
      shell: systemctl is-active nginx
      register: nginx_status
      changed_when: false

    - name: Display Nginx status
      debug:
        msg: "Nginx service is {{ nginx_status.stdout }}"
